---

- name: Set up virtualbox and vagrant
  hosts: all
  gather_facts: true
  become: true
  roles:
    - virtualbox
    - vagrant

- name: Run vagrant up
  # Split in two plays to run as non root user
  hosts: all
  tasks:
    - name: vagrant init
      command: vagrant init --force ubuntu/focal64

    - name: vagrant up
      command: vagrant up
      failed_when: false
