---
- name: Lint
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: yamllint
      ansible.builtin.command: yamllint ../..
    - name: ansible-lint
      ansible.builtin.command: ansible-lint ../..

- name: Prepare
  hosts: molecule
  gather_facts: false
  tasks:
    - name: Prepare playbook
      ansible.builtin.meta: noop
