---
# github_cli/tasks/main.yml

- name: Install required packages
  ansible.builtin.apt:
    name:
      - curl
      - gpg-agent
    state: present
    cache_valid_time: 600

- name: Get DEB architecture
  ansible.builtin.command: "dpkg --print-architecture"
  register: deb_architecture
  failed_when: deb_architecture.rc != 0
  changed_when: false

- name: Print DEB architecture
  ansible.builtin.debug:
    msg: "deb_architecture: {{ deb_architecture.stdout }}"

- name: Add the GPG key for the GitHub CLI tool's package repository
  ansible.builtin.apt_key:
    url: https://cli.github.com/packages/githubcli-archive-keyring.gpg
    keyring: /usr/share/keyrings/githubcli-archive-keyring.gpg

- name: Add the GitHub CLI repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ deb_architecture.stdout }} signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
    state: present

- name: Install the GitHub CLI tool
  ansible.builtin.apt:
    name: gh
    state: present
    update_cache: true
