---
- name: Verify
  hosts: all
  gather_facts: false
  vars_files:
    - ../../defaults/main.yml
  tasks:
    - name: Verify VirtualBox version
      ansible.builtin.command: "VBoxManage --version"
      register: vbox_version
    - name: Assert vagrant version
      ansible.builtin.assert:
        that: "vbox_version.stdout.split('.')[0:2] == virtualbox_version.split('.')"
        fail_msg: "Vagrant installation failed"
        success_msg: "{{ vbox_version.stdout }}"
