---
dependency:
  name: galaxy
  options:
    requirements-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: vagrant-ubuntu
    box: ubuntu/bionic64
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 80, host: 8088"

provisioner:
  name: ansible
  log: true
  scenarios:
    - name: default
  config_options:
    defaults:
      remote_user: vagrant
      private_key_file: /home/runner/.ssh/id_rsa
      host_key_checking: false
      forks: 100
      force_handlers: true