---
- name: Verify
  hosts: molecule
  gather_facts: false
  tasks:
    - name: Verify VirtualBox version
      ansible.builtin.shell: "VBoxManage --version"
      register: vagrant_version
    - name: Assert vagrant version
      ansible.builtin.assert:
        that: "'Vagrant' in vagrant_version.stdout"
        fail_msg: "Vagrant installation failed"
        success_msg: "{{ vagrant_version.stdout }}"
