---
- name: Verify
  hosts: all
  gather_facts: false
  vars_files:
    - ../../defaults/main.yml
  tasks:
    - name: Check if MOK keys are present
      ansible.builtin.stat:
        path: "{{ secure_boot_machine_owner_key_mok_path }}/{{ item }}"
      register: result
      loop:
        - MOK.der
        - MOK.priv
        - MOK.pem

    - name: Fail if MOK keys are not present
      ansible.builtin.fail:
        msg: "MOK key {{ item.item }} does not exist"
      when: not item.stat.exists
      loop: "{{ result.results }}"