---
- name: Verify
  hosts: molecule
  gather_facts: false
  tasks:
    - name: Verify github cli is installed
      ansible.builtin.apt:
        name: gh
        state: present
        update_cache: no
