---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Verify github cli is installed
      ansible.builtin.command: gh --version
      register: gh_version

    - name: Fail if github cli is not installed
      ansible.builtin.fail:
        msg: "GitHub CLI is not installed"
      when: gh_version.rc != 0
