---
# secure_boot_machine_owner_key/tasks/main.yml

- name: Install required packages
  ansible.builtin.apt:
    name:
      - openssl
    state: present
    update_cache: true

- name: Assert MOK key don't exist in
  ansible.builtin.stat:
    path: "{{ secure_boot_machine_owner_key_mok_path }}/{{ item }}"
  loop:
    - MOK.der
    - MOK.priv
  register: mok_key_state

- name: Check if MOK key exist
  ansible.builtin.set_fact:
    mok_key_exist: "{{ (mok_key_state.results | map(attribute='stat.exists') | list) is all }}"

- name: Create MOK keys
  when: not mok_key_exist
  block:

    - name: Create MOK key directory
      ansible.builtin.file:
        path: /var/lib/shim-signed/mok
        state: directory
        mode: '0700'

    - name: Generate MOK private key
      ansible.builtin.command: >
        openssl req -nodes -new -x509 -newkey rsa:2048
        -keyout {{ secure_boot_machine_owner_key_mok_path }}/MOK.priv
        -outform DER -out {{ secure_boot_machine_owner_key_mok_path }}/MOK.der -days 36500 -subj "/CN=My Name/"
      changed_when: not mok_key_exist

    - name: Generate MOK PEM key
      ansible.builtin.command: >
        openssl x509 -inform der -in {{ secure_boot_machine_owner_key_mok_path }}/MOK.der
        -out {{ secure_boot_machine_owner_key_mok_path }}/MOK.pem
      changed_when: not mok_key_exist
